<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYyt3Br5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYyt3Br5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYyt3Br5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYyt3Br5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYyt3Br5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yyt3Br5',
    'container.build_id' => '54af9945',
    'container.build_time' => 1616057940,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYyt3Br5');
